### ISSUE TITLE
The BLEU-2 scores for text planning reported in the paper

### ISSUE THREAD

**Issue by EagleW** [zhaochaocs/DualEnc#2]
Dear Authors,

For the BLEU-2 scores reported in table 1 of the paper, how do you calculate the accuracy and BLEU-2. Will you evaluate the text plan by converting the triple ids back to the triple text and concatenate them together or merely comparing the index? Thank you very much!

**Comment by EagleW** [comment]
Also, could you elaborate on how to compute the accuracy?

**Comment by happycjksh** [comment]
I don't know how to calculate the BLEU-2. Can you tell me?
