### ISSUE TITLE
How to use the glove embedding?

### ISSUE THREAD

**Issue by QipengGuo** [zhaochaocs/DualEnc#4]
Dear author,
It seems that the code of using glove embedding is commented, and I have fixed it manually by using the gensim package. The remaining question is that the hit ratio on the test set is 85% (is it correct?), and the performance gain is very little for the planner, the accuracy only increases 1 point, which from 54 to 55. Btw, you mentioned that it needs to use the non-delex and delex model for seen and unseen test data. Is this part included in the code?

Looking forward to your feedback. :)

**Comment by zhaochaocs** [comment]
Hello Qipeng, thanks for the questions. I didn't use glove embedding in the final model since it gave little performance, maybe partially because of the low hit ratio on the test set. 85% looks like a decent hit ratio. You can switch between two models using `if_delex` in the shell script.
