### ISSUE TITLE
Cannot reproduce the result

### ISSUE THREAD

**Issue by xc15071347094** [zhaochaocs/DualEnc#9]
Hi Mr.Zhao
    We recently read this paper, which is very well written, well-structured. Therefore, we have carried out the reproducing work of the paper. In the process of reproducing, regarding the "Seen data", the experimental results have not reached the effect of the paper, so if it is convenient, can you provide the relevant results and data in the experiment? , Such as the final generated text. This will also better prove the validity of your work.  Thank you very much!

Yours Sincerely
Winston

**Comment by zhaochaocs** [comment]
Output sent by email. 

For evaluation, please follow the official evaluation scripts. Different scripts may have dramatically different results.
https://webnlg-challenge.loria.fr/challenge_2017/
